Add webring maintenance scripts and GitHub action
hackclub/webring pull request #44
Opened 2021-01-11 14:33 UTC by KhushrajRathod

Closes https://github.com/hackclub/webring/issues/43

The main members.json file (the one to be editing by future members) has been moved to the top level. The one inside public/ is generated every 15 minutes.

2021-01-11 14:56 UTC, googol88 commented
This really cool!! Just one thing, do you think 15 minutes is too often? Maybe we can change it to once a day instead...
Also I haven't worked with Actions before so I'll wait to see what sam thinks.
Really neat work!

2021-01-12 00:55 UTC, sampoder requested changes

2021-01-12 00:55 UTC, sampoder commented on .github/workflows/maintenance.yml
> +        git commit -m "Maintain Webring" -a --allow-empty
Could we remove this? Would reduce spamming the commit history.

2021-01-12 00:56 UTC, sampoder commented
Otherwise, I'm pretty happy with this.

2021-01-12 03:37 UTC, KhushrajRathod commented
@sampoder not sure how but....
Without --allow-empty, I'd have to make it succeed anyway with `|| true`, and that'd also make the push fail (right?).
I'll give it a go

2021-01-12 03:51 UTC, sampoder approved these changes

2021-01-12 03:52 UTC, merged

2021-01-12 03:53 UTC, sampoder commented
Perfecto, that seemed to work @KhushrajRathod!

2021-01-12 12:29 UTC, googol88 commented
Woohoo! This is a really nice addition!